server:
  port: 19092
spring:
  application:
    name: auth-server
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        highlight_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: mypassword

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"
  expiration: 3600000
